### ISSUE TITLE
What should I update? :)

### ISSUE THREAD

**Issue by for-coursera** [skamsie/vim-news-headlines#2]
Got the following:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/for-coursera/.vim/plugged/vim-news-headlines/ftplugin/news_headlines.py", line 181, in main
    headlines = news.get_top_headlines(sources)
  File "/Users/for-coursera/.vim/plugged/vim-news-headlines/ftplugin/news_headlines.py", line 78, in get_top_headlines
    response = json.loads(urlopen(url, timeout=5).read().decode('utf-8'))
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by skamsie** [comment]
Looking at the error looks like it's returned by apinews itself. It could be one of two:

1. Either the request is indeed bad (for example you set ```g:news_headlines_sources``` to something unsupported, like non-existing source or maybe you have whitespaces). Also check the value of the api key that you've set... should also not have any trailing characters

2. I see your vim uses python 3, I just checked and both my vim and neovim have only python2 support. I assumed I took all the precautions to make it work with both versions, but maybe I was wrong... I will test

**Comment by skamsie** [comment]
Ok, I tested with vim compiled only with python 3 support and it is not working but because of o completely different issue than mentioned by you. You problem is most likely improperly set `g:news_headlines_sources`. I will make a fix to add python3 support

**Comment by skamsie** [comment]
@for-coursera I have added [python3 support](https://github.com/skamsie/vim-news-headlines/commit/ef2adf763b48c1422df1989f53e33537c8b6b607) and tested locally. Everything should work fine now. Please update and try again without any additional settings.

If you are using Plug, you can update with: ```:PlugUpdate```

**Comment by for-coursera** [comment]
Yep, problem was the `sources` var. Thanks and sorry :).

**Comment by skamsie** [comment]
No worries, thanks for reporting :)
